- name: Install curl (dependency)
  ansible.builtin.apt:
    name: curl
    state: present
    update_cache: yes
  when: ansible_os_family == "Debian"
  become: true

- name: Download Netdata installer script
  ansible.builtin.get_url:
    url: https://my-netdata.io/kickstart.sh
    dest: /tmp/kickstart.sh
    mode: '0755'
  become: true

- name: Install Netdata from downloaded script
  ansible.builtin.command: bash /tmp/kickstart.sh --dont-wait
  args:
    creates: /opt/netdata
  become: true
