- name: Enable nginx1 via amazon-linux-extras (Amazon Linux 2)
  ansible.builtin.command: amazon-linux-extras enable nginx1
  when: ansible_distribution == "Amazon" and ansible_distribution_major_version == "2"
  become: true

- name: Install nginx on Amazon Linux 2
  ansible.builtin.yum:
    name: nginx
    state: present
  when: ansible_distribution == "Amazon" and ansible_distribution_major_version == "2"
  become: true

- name: Install nginx on Debian-based systems
  ansible.builtin.apt:
    name: nginx
    state: present
    update_cache: yes
  when: ansible_os_family == "Debian"
  become: true

- name: Start and enable nginx
  ansible.builtin.service:
    name: nginx
    state: started
    enabled: yes
  become: true

- name: Copy nginx reverse proxy config
  ansible.builtin.template:
    src: nginx.conf.j2
    dest: /etc/nginx/nginx.conf
    mode: '0644'
  notify: restart nginx
  become: true
